// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OOP4200_Tarneeb.DbContexts;

namespace OOP4200_Tarneeb.Migrations
{
    [DbContext(typeof(TarneebDbContext))]
    partial class TarneebDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.16");

            modelBuilder.Entity("OOP4200_Tarneeb.DTOs.LogDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventActor")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventDetails")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("OOP4200_Tarneeb.DTOs.StatsDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumGames")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumLosses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumWins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("707e21b6-9a17-440d-a2f7-626c0637170f"),
                            NumGames = 0,
                            NumLosses = 0,
                            NumWins = 0,
                            PlayerName = "Player 1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
